<a href="https://colab.research.google.com/github/sunny0625/ML-Project/blob/master/P_2_Mobile_Price_Classification.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Importing pandas model
import pandas as pd

In [26]:
# !git clone git@github.com:sunny0625/ML-Project.git

Cloning into 'ML-Project'...
Host key verification failed.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

In [2]:
# Importing Dataset
price_data = pd.read_csv("https://www.dropbox.com/s/iy0w25eunwx2qlq/MobilePriceClassification.csv?dl=1")

In [3]:
# Exploring Dataset
price_data.head()

,battery_power,blue,clock_speed,dual_sim,fc,four_g,int_memory,m_dep,mobile_wt,n_cores,...,px_height,px_width,ram,sc_h,sc_w,talk_time,three_g,touch_screen,wifi,price_range
0,842,0,2.2,0,1,0,7,0.6,188,2,...,20,756,2549,9,7,19,0,0,1,1
1,1021,1,0.5,1,0,1,53,0.7,136,3,...,905,1988,2631,17,3,7,1,1,0,2
2,563,1,0.5,1,2,1,41,0.9,145,5,...,1263,1716,2603,11,2,9,1,1,0,2
3,615,1,2.5,0,0,0,10,0.8,131,6,...,1216,1786,2769,16,8,11,1,0,0,2
4,1821,1,1.2,0,13,1,44,0.6,141,2,...,1208,1212,1411,8,2,15,1,1,0,1

In [4]:
price_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   battery_power  2000 non-null   int64
 1   blue           2000 non-null   int64
 2   clock_speed    2000 non-null   float64
 3   dual_sim       2000 non-null   int64
 4   fc             2000 non-null   int64
 5   four_g         2000 non-null   int64
 6   int_memory     2000 non-null   int64
 7   m_dep          2000 non-null   float64
 8   mobile_wt      2000 non-null   int64
 9   n_cores        2000 non-null   int64
 10  pc             2000 non-null   int64
 11  px_height      2000 non-null   int64
 12  px_width       2000 non-null   int64
 13  ram            2000 non-null   int64
 14  sc_h           2000 non-null   int64
 15  sc_w           2000 non-null   int64
 16  talk_time      2000 non-null   int64
 17  three_g        2000 non-null   int64
 18  touch_screen   2000 non-null   int64
 19  wifi           2000 non-null   int64
 20  price_range    2000 non-null   int64
dtypes: float64(2), int64(19)
memory usage: 328.2 KB

In [5]:
price_data.value_counts()

battery_power  blue  clock_speed  dual_sim  fc  four_g  int_memory  m_dep  mobile_wt  n_cores  pc  px_height  px_width  ram   sc_h  sc_w  talk_time  three_g  touch_screen  wifi  price_range
501            0     2.3          0         12  1       54          0.3    131        4        19  504        1089      2346  13    12    2          1        0             1     1              1
1494           0     1.9          0         2   1       47          0.4    129        2        9   207        1177      3202  13    1     14         1        0             0     3              1
1504           0     1.9          1         7   1       25          0.3    152        4        9   395        1853      1788  13    11    13         1        0             1     1              1
                     1.5          0         12  1       34          0.7    142        8        15  507        973       2806  7     2     7          1        0             1     2              1
1503           1     0.7          0         10  1       43          0.2    166        4        14  841        1304      2122  15    1     2          1        0             0     2              1
                                                                                                                                                                                                ..
972            1     1.7          0         0   1       54          0.7    107        3        4   681        1050      1900  16    8     19         1        0             1     1              1
                     1.3          0         8   0       44          0.7    82         7        10  297        589       3925  7     6     7          0        1             0     3              1
                     0.5          1         5   0       13          0.4    193        5        8   1392       1795      1615  11    6     13         0        1             0     1              1
970            1     1.3          1         5   0       59          0.2    84         7        19  1765       1786      3675  12    0     12         0        0             0     3              1
1998           1     1.2          0         8   0       31          0.6    196        8        19  50         1356      2311  17    9     18         1        1             0     2              1
Length: 2000, dtype: int64

In [6]:
price_data.corr()

,battery_power,blue,clock_speed,dual_sim,fc,four_g,int_memory,m_dep,mobile_wt,n_cores,...,px_height,px_width,ram,sc_h,sc_w,talk_time,three_g,touch_screen,wifi,price_range
battery_power,1.000000,0.011252,0.011482,-0.041847,0.033334,0.015665,-0.004004,0.034085,0.001844,-0.029727,...,0.014901,-0.008402,-0.000653,-0.029959,-0.021421,0.052510,0.011522,-0.010516,-0.008343,0.200723
blue,0.011252,1.000000,0.021419,0.035198,0.003593,0.013443,0.041177,0.004049,-0.008605,0.036161,...,-0.006872,-0.041533,0.026351,-0.002952,0.000613,0.013934,-0.030236,0.010061,-0.021863,0.020573
clock_speed,0.011482,0.021419,1.000000,-0.001315,-0.000434,-0.043073,0.006545,-0.014364,0.012350,-0.005724,...,-0.014523,-0.009476,0.003443,-0.029078,-0.007378,-0.011432,-0.046433,0.019756,-0.024471,-0.006606
dual_sim,-0.041847,0.035198,-0.001315,1.000000,-0.029123,0.003187,-0.015679,-0.022142,-0.008979,-0.024658,...,-0.020875,0.014291,0.041072,-0.011949,-0.016666,-0.039404,-0.014008,-0.017117,0.022740,0.017444
fc,0.033334,0.003593,-0.000434,-0.029123,1.000000,-0.016560,-0.029133,-0.001791,0.023618,-0.013356,...,-0.009990,-0.005176,0.015099,-0.011014,-0.012373,-0.006829,0.001793,-0.014828,0.020085,0.021998
four_g,0.015665,0.013443,-0.043073,0.003187,-0.016560,1.000000,0.008690,-0.001823,-0.016537,-0.029706,...,-0.019236,0.007448,0.007313,0.027166,0.037005,-0.046628,0.584246,0.016758,-0.017620,0.014772
int_memory,-0.004004,0.041177,0.006545,-0.015679,-0.029133,0.008690,1.000000,0.006886,-0.034214,-0.028310,...,0.010441,-0.008335,0.032813,0.037771,0.011731,-0.002790,-0.009366,-0.026999,0.006993,0.044435
m_dep,0.034085,0.004049,-0.014364,-0.022142,-0.001791,-0.001823,0.006886,1.000000,0.021756,-0.003504,...,0.025263,0.023566,-0.009434,-0.025348,-0.018388,0.017003,-0.012065,-0.002638,-0.028353,0.000853
mobile_wt,0.001844,-0.008605,0.012350,-0.008979,0.023618,-0.016537,-0.034214,0.021756,1.000000,-0.018989,...,0.000939,0.000090,-0.002581,-0.033855,-0.020761,0.006209,0.001551,-0.014368,-0.000409,-0.030302
n_cores,-0.029727,0.036161,-0.005724,-0.024658,-0.013356,-0.029706,-0.028310,-0.003504,-0.018989,1.000000,...,-0.006872,0.024480,0.004868,-0.000315,0.025826,0.013148,-0.014733,0.023774,-0.009964,0.004399
pc,0.031441,-0.009952,-0.005245,-0.017143,0.644595,-0.005598,-0.033273,0.026282,0.018844,-0.001193,...,-0.018465,0.004196,0.028984,0.004938,-0.023819,0.014657,-0.001322,-0.008742,0.005389,0.033599
px_height,0.014901,-0.006872,-0.014523,-0.020875,-0.009990,-0.019236,0.010441,0.025263,0.000939,-0.006872,...,1.000000,0.510664,-0.020352,0.059615,0.043038,-0.010645,-0.031174,0.021891,0.051824,0.148858
px_width,-0.008402,-0.041533,-0.009476,0.014291,-0.005176,0.007448,-0.008335,0.023566,0.000090,0.024480,...,0.510664,1.000000,0.004105,0.021599,0.034699,0.006720,0.000350,-0.001628,0.030319,0.165818
ram,-0.000653,0.026351,0.003443,0.041072,0.015099,0.007313,0.032813,-0.009434,-0.002581,0.004868,...,-0.020352,0.004105,1.000000,0.015996,0.035576,0.010820,0.015795,-0.030455,0.022669,0.917046
sc_h,-0.029959,-0.002952,-0.029078,-0.011949,-0.011014,0.027166,0.037771,-0.025348,-0.033855,-0.000315,...,0.059615,0.021599,0.015996,1.000000,0.506144,-0.017335,0.012033,-0.020023,0.025929,0.022986
sc_w,-0.021421,0.000613,-0.007378,-0.016666,-0.012373,0.037005,0.011731,-0.018388,-0.020761,0.025826,...,0.043038,0.034699,0.035576,0.506144,1.000000,-0.022821,0.030941,0.012720,0.035423,0.038711
talk_time,0.052510,0.013934,-0.011432,-0.039404,-0.006829,-0.046628,-0.002790,0.017003,0.006209,0.013148,...,-0.010645,0.006720,0.010820,-0.017335,-0.022821,1.000000,-0.042688,0.017196,-0.029504,0.021859
three_g,0.011522,-0.030236,-0.046433,-0.014008,0.001793,0.584246,-0.009366,-0.012065,0.001551,-0.014733,...,-0.031174,0.000350,0.015795,0.012033,0.030941,-0.042688,1.000000,0.013917,0.004316,0.023611
touch_screen,-0.010516,0.010061,0.019756,-0.017117,-0.014828,0.016758,-0.026999,-0.002638,-0.014368,0.023774,...,0.021891,-0.001628,-0.030455,-0.020023,0.012720,0.017196,0.013917,1.000000,0.011917,-0.030411
wifi,-0.008343,-0.021863,-0.024471,0.022740,0.020085,-0.017620,0.006993,-0.028353,-0.000409,-0.009964,...,0.051824,0.030319,0.022669,0.025929,0.035423,-0.029504,0.004316,0.011917,1.000000,0.018785
price_range,0.200723,0.020573,-0.006606,0.017444,0.021998,0.014772,0.044435,0.000853,-0.030302,0.004399,...,0.148858,0.165818,0.917046,0.022986,0.038711,0.021859,0.023611,-0.030411,0.018785,1.000000

In [7]:
price_data.describe()

,battery_power,blue,clock_speed,dual_sim,fc,four_g,int_memory,m_dep,mobile_wt,n_cores,...,px_height,px_width,ram,sc_h,sc_w,talk_time,three_g,touch_screen,wifi,price_range
count,2000.000000,2000.0000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,...,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000
mean,1238.518500,0.4950,1.522250,0.509500,4.309500,0.521500,32.046500,0.501750,140.249000,4.520500,...,645.108000,1251.515500,2124.213000,12.306500,5.767000,11.011000,0.761500,0.503000,0.507000,1.500000
std,439.418206,0.5001,0.816004,0.500035,4.341444,0.499662,18.145715,0.288416,35.399655,2.287837,...,443.780811,432.199447,1084.732044,4.213245,4.356398,5.463955,0.426273,0.500116,0.500076,1.118314
min,501.000000,0.0000,0.500000,0.000000,0.000000,0.000000,2.000000,0.100000,80.000000,1.000000,...,0.000000,500.000000,256.000000,5.000000,0.000000,2.000000,0.000000,0.000000,0.000000,0.000000
25%,851.750000,0.0000,0.700000,0.000000,1.000000,0.000000,16.000000,0.200000,109.000000,3.000000,...,282.750000,874.750000,1207.500000,9.000000,2.000000,6.000000,1.000000,0.000000,0.000000,0.750000
50%,1226.000000,0.0000,1.500000,1.000000,3.000000,1.000000,32.000000,0.500000,141.000000,4.000000,...,564.000000,1247.000000,2146.500000,12.000000,5.000000,11.000000,1.000000,1.000000,1.000000,1.500000
75%,1615.250000,1.0000,2.200000,1.000000,7.000000,1.000000,48.000000,0.800000,170.000000,7.000000,...,947.250000,1633.000000,3064.500000,16.000000,9.000000,16.000000,1.000000,1.000000,1.000000,2.250000
max,1998.000000,1.0000,3.000000,1.000000,19.000000,1.000000,64.000000,1.000000,200.000000,8.000000,...,1960.000000,1998.000000,3998.000000,19.000000,18.000000,20.000000,1.000000,1.000000,1.000000,3.000000

In [8]:
price_data.nunique()

battery_power    1094
blue                2
clock_speed        26
dual_sim            2
fc                 20
four_g              2
int_memory         63
m_dep              10
mobile_wt         121
n_cores             8
pc                 21
px_height        1137
px_width         1109
ram              1562
sc_h               15
sc_w               19
talk_time          19
three_g             2
touch_screen        2
wifi                2
price_range         4
dtype: int64

In [9]:
price_data.shape

(2000, 21)

In [10]:
price_data.columns

Index(['battery_power', 'blue', 'clock_speed', 'dual_sim', 'fc', 'four_g',
       'int_memory', 'm_dep', 'mobile_wt', 'n_cores', 'pc', 'px_height',
       'px_width', 'ram', 'sc_h', 'sc_w', 'talk_time', 'three_g',
       'touch_screen', 'wifi', 'price_range'],
      dtype='object')

In [11]:
# Define X
X = price_data[['battery_power', 'blue', 'clock_speed', 'dual_sim', 'fc', 'four_g',
       'int_memory', 'm_dep', 'mobile_wt', 'n_cores', 'pc', 'px_height',
       'px_width', 'ram', 'sc_h', 'sc_w', 'talk_time', 'three_g',
       'touch_screen', 'wifi']]

In [12]:
# Define y
y = price_data['price_range']

In [13]:
# Importing Train Test Model
from sklearn.model_selection import train_test_split

In [18]:
# Spliting X & y into Training & Testing Data
X_train, X_test, y_train, y_test = train_test_split(X, y, train_size = 0.8, random_state = 25)

In [15]:
X_train

,battery_power,blue,clock_speed,dual_sim,fc,four_g,int_memory,m_dep,mobile_wt,n_cores,pc,px_height,px_width,ram,sc_h,sc_w,talk_time,three_g,touch_screen,wifi
1367,598,1,0.8,1,8,1,62,0.1,117,8,9,118,764,3066,11,2,19,1,1,0
1809,683,1,2.1,0,7,0,30,0.1,197,7,8,927,1135,2066,9,0,15,0,0,0
973,516,1,0.7,1,1,0,30,0.9,138,1,12,126,698,3731,17,13,15,0,0,0
182,1082,0,0.8,0,0,0,38,0.1,198,8,5,986,1191,2337,6,1,17,0,1,1
871,712,1,1.6,0,6,1,9,0.8,172,2,14,881,1234,3612,13,5,4,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1341,1423,0,0.6,0,12,0,44,0.8,131,5,13,501,640,2253,10,8,9,0,0,0
143,786,0,2.2,1,0,0,33,0.5,141,7,6,507,1697,2390,12,11,5,1,0,1
474,1968,0,0.9,0,0,0,22,0.8,115,3,7,861,1259,2323,9,8,7,0,0,1
318,508,0,0.8,0,7,1,42,0.3,94,1,8,39,557,663,13,12,7,1,0,0
1156,1732,0,0.8,0,2,0,61,0.3,172,5,3,201,656,3940,17,11,20,0,1,1

In [16]:
# Importing Model to train ML Model
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier()

In [19]:
# Train the ML Model
knn.fit(X_train, y_train)

KNeighborsClassifier()

In [21]:
# Testing the Model
y_pred = knn.predict(X_test)

In [22]:
# model accuracy
from sklearn.metrics import accuracy_score, classification_report

In [23]:
accuracy_score(y_test, y_pred)

0.91

In [24]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.97      0.95      0.96        96
           1       0.88      0.95      0.92       103
           2       0.90      0.85      0.87       112
           3       0.90      0.90      0.90        89

    accuracy                           0.91       400
   macro avg       0.91      0.91      0.91       400
weighted avg       0.91      0.91      0.91       400